### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by scafroglia93**
- CRC Check is disable by default but, with 0644 perm it's possible pilot this function with kernel tweaking app like adiutor ecc ecc. Save 30% cost performance
- Config Jump Label improve total system performance
- New Defconfig for better developing

### CODE REVIEW

**Comment by wasd--** [comment]
Nice the new defconfig, the old one was a mess.

**Comment by nofearnohappy** [comment]
Do not cover the pool

**Comment by nofearnohappy** [comment]
I later look

**Comment by scafroglia93** [comment]
Keep me update

**Pull request closed without merging**
