### PR TITLE
random: Increase entropy threshold

### PR DESCRIPTION
**Pull request by supersonicninja**
This should make internet connections faster and more stable.

### CODE REVIEW

**Comment by nofearnohappy** [comment]
I do not understand what it gives

**Comment by supersonicninja** [comment]
Its the threshold of "randomness(entropy)".
If "randomness" values go under these values, it will start to replenish.
This "randomness" is most heavily used by Wi-Fi encryption, and SSL websites.
If this "randomness" is out, your web browsing will be stuck until it replenishes.
So this commit will make sure the large "randomness" stock is available for any time.
It is sort of a little speed-up tweak.

**Comment by DeicPro** [comment]
@supersonicninja that drains battery & is not good idea to stock CM build... This is not a custom CM ROM (or that I think).

**Comment by supersonicninja** [comment]
@DeicPro Okay. closing this.

**Pull request closed without merging**
